# Simple development docker-compose
# Usage: docker-compose -f docker-compose.simple.yml up --build

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_APP_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=https://api-dev.omniflows.com
      - NEXT_PUBLIC_APP_VERSION=development
    restart: unless-stopped